# Main settings

# Number of kids we are assigning
kCount: 50

# number of cabins
cabins: 5

# For Data Generator only
case: B
chainLength: 12
avgChainLength: 7

# Preferences file
# KID1, KID2, PREF
dataFile: tmp/data-k50-c5-7-B.csv

# output for KidsCabin and input for visualizer
# What are the assignments
assingments: tmp/assignment-k50-c5-7-B.csv

# The sets of kids. This is if you used a data generator
setFile: tmp/sets-k50-c5-7-B.csv

# Visualizer Settings

# Set file contains the intended sets


