# Main settings
name: Stable Room mate k6 c3

# Number of kids we are assigning
kCount: 4

# number of cabins
cabins: 2

# max number of kids per cabin
kPerCabin: 2

# For Data Generator only
case: SR

# Preferences file
# KID1, KID2, PREF
dataFile: tmp/data-k4-c2-SR-2-U.csv

# output for KidsCabin and input for visualizer
# What are the assignments
assignments: tmp/assignment-k4-c2-SR-2-U.csv

# The sets of kids. This is if you used a data generator
setFile: tmp/sets-k4-c2-SR-2-U.csv

# Visualizer Settings

# Set file contains the intended sets


