# Main settings
name: Stable Room mate k6 c3

# Number of kids we are assigning
kCount: 6

# number of cabins
cabins: 3

# max number of kids per cabin
kPerCabin: 2

# For Data Generator only
case: SR

# Preferences file
# KID1, KID2, PREF
dataFile: tmp/data-k6-c3-SR-1.csv

# output for KidsCabin and input for visualizer
# What are the assignments
assignments: tmp/assignment-k6-c3-SR-1.csv

# The sets of kids. This is if you used a data generator
setFile: tmp/sets-k6-c3-SR-1.csv

# Visualizer Settings

# Set file contains the intended sets


