# Main settings

# Number of kids we are assigning
kCount: 500

# number of cabins
cabins: 52

# max number of kids per cabin
kPerCabin: 10

# For Data Generator only
case: C
chainLength: 12
avgChainLength: 8
sd: 3.0

# Preferences file
# KID1, KID2, PREF
dataFile: tmp/data-k500-c50-C1.csv

# output for KidsCabin and input for visualizer
# What are the assignments
assingments: tmp/assignment-k500-c50-C1.csv

# The sets of kids. This is if you used a data generator
setFile: tmp/sets-k500-c50-C1.csv

# Visualizer Settings

# Set file contains the intended sets


