# Main settings
name: Stable Marriage k12 c6

# Number of kids we are assigning
kCount: 12

# number of cabins
cabins: 6

# max number of kids per cabin
kPerCabin: 2

# For Data Generator only
case: SM

# Preferences file
# KID1, KID2, PREF
dataFile: tmp/data-k12-c6-SM1.csv

# output for KidsCabin and input for visualizer
# What are the assignments
assignments: tmp/assignment-k12-c6-SM1.csv

# The sets of kids. This is if you used a data generator
setFile: tmp/sets-k12-c6-SM1.csv

# Visualizer Settings

# Set file contains the intended sets


